name: Build & Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
  

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: file-encrypter
            asset_name: file-encrypter-linux
          - os: windows-latest
            artifact_name: file-encrypter.exe
            asset_name: file-encrypter-windows.exe
          - os: macos-latest
            artifact_name: file-encrypter
            asset_name: file-encrypter-macos

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --locked
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        release_name: "Release"
        tag: ${{ github.ref }}
        body: "Automatic Release"
        overwrite: true
